### ISSUE TITLE
Code Refactoring for dashboard folder (Camel Casing)

### ISSUE THREAD

**Issue by ojimba01** [phlask/phlask-data-handlers#17]
Since the project is maturing and it's gaining more usage and collaborators, we should make sure to keep our code clean and follow some styling guidelines! For now we will follow the camel casing style for all of our function and class names.

Below is an example of what the refactor should like.

Example:
get_changed_data()

Camel Cased:
getChangedData():

Please follow this style for ALL of the functions and Classes!

**Comment by tarunsamanta2k20** [comment]
I would like to work on this issue.
