### ISSUE TITLE
Validating Pre-Existing Data

### ISSUE THREAD

**Issue by ojimba01** [phlask/phlask-data-handlers#24]
**Overview**
In the Phlask project, we're using Firebase Realtime Database to store information about various resources, including Water, Food, Bathroom, and Forage. To ensure data quality and consistency, we need to create data validation scripts to check and validate the existing data and data structures in our Firebase Realtime Database.

**Task**
We need a Python developer with experience using Firebase Admin SDK to create validation scripts for each of the following resources:
- Water
- Food
- Bathroom
- Forage

**The validation scripts should:**
1. Connect to the Firebase Realtime Database using the Firebase Admin SDK.
2. Check the structure and content of the data for each resource.
3. Validate the data against a pre-defined schema.
4. Report any inconsistencies, errors, or missing data.
5. Optionally, suggest or apply fixes for the issues found (if within the scope of the issue).

**Requirements**
Python programming experience.
Familiarity with Firebase Admin SDK and Firebase Realtime Database.
Ability to design and implement data validation and error handling mechanisms.

**Steps to complete this task**
1. Familiarize yourself with the existing data structures in our Firebase Realtime Database.
2. Design a data validation schema for each resource type (Water, Food, Bathroom, Forage).
3. Write the validation scripts using Python and Firebase Admin SDK, ensuring that they validate the data against the defined schema.
4. Test the scripts on our Firebase Realtime Database and report the results.
5. If applicable, discuss potential fixes for the issues found.
[Link to data schemas](https://cacoo.com/diagrams/V16Tqh405C1sOwf6/0FE3B)

Please provide an estimate of the time needed to complete this task and any other information you might need to get started. We appreciate your contribution to the Phlask project!

**Comment by kdmonroe** [comment]
I'll take this!

**Comment by kdmonroe** [comment]
Hello team - After going through the water tap database outputs and validation results, I've noted a few points that could help improve our data quality and consistency:

- Consider removing entries where `access == "TrashAcademy"`. These appear to be test entries, as they're the only ones populating fields `["active", "direction", "ill", "impressions", "tab_id", "unit"]`.
- Rename `zip` to `zip_code` per the [database diagram](https://cacoo.com/diagrams/V16Tqh405C1sOwf6/0FE3B).
- Transfer business hours notes from `description` into `hours`. Verify any correlation. 
- For rows with `lat` and `lon` but lack an `address` - we could use reverse geocoding to fill them in. 
- Verify entries with duplicate `address`
- Populate the entries with business `hours` too short (12 total at present). 
- **All Resources** - Create text descriptions for each field. 

I hope these recommendations are helpful + look forward to discussing them further!
