### ISSUE TITLE
Optimize Webapp Dashboard Loading Speed

### ISSUE THREAD

**Issue by ojimba01** [phlask/phlask-data-handlers#4]
Currently upon loading the web app locally it takes a VERY long time (around ~50 seconds) to have the site be populated with the data from phlask's database. There are ways to optimize the load time by using JavaScript to handle how much data is loaded onto a visible part of the web app. We will need someone to look into approaches to solve this problem so we can implement sooner than later.

**Comment by kdmonroe** [comment]
I can take this one!

**Comment by ojimba01** [comment]
@kdmonroe That'd be great! I just assigned you to this issue!
